/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cekideal;

import javax.swing.JOptionPane;

/**
 *
 * @author Arya
 */
public class JCek extends javax.swing.JFrame {
    String temp = "";
    double ti,b1,h1;
    /**
     * Creates new form JCek
     */
    public JCek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tinggi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lk = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        berat = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ideal1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(14, 60, 80, 14);

        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        getContentPane().add(d2);
        d2.setBounds(40, 440, 370, 30);

        jLabel2.setText("Kg");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 290, 80, 14);
        getContentPane().add(tinggi);
        tinggi.setBounds(130, 90, 80, 30);

        jLabel4.setText("Berat Badan :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(14, 140, 80, 14);

        buttonGroup1.add(lk);
        lk.setText("Laki");
        lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lkActionPerformed(evt);
            }
        });
        getContentPane().add(lk);
        lk.setBounds(130, 170, 100, 23);

        buttonGroup1.add(pr);
        pr.setText("Perempuan");
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        getContentPane().add(pr);
        pr.setBounds(270, 170, 160, 23);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(323, 220, 90, 23);

        jButton2.setText("Hitung");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 220, 90, 23);

        jButton3.setText("Coba Lagi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 220, 110, 23);

        jLabel5.setText("Jenis Kelamin : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 80, 14);
        getContentPane().add(berat);
        berat.setBounds(130, 130, 80, 30);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(130, 50, 260, 30);

        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        getContentPane().add(d1);
        d1.setBounds(40, 400, 370, 30);

        jLabel6.setText("Tinggi :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(14, 100, 80, 14);

        jLabel8.setText("Kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 140, 80, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cek Ideal Tubuh");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 0, 180, 50);
        getContentPane().add(ideal1);
        ideal1.setBounds(130, 280, 80, 30);

        jLabel10.setText("cm");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 100, 80, 14);

        jLabel11.setText("Berat  badan ideal anda adalah : ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 260, 180, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Hasil Analsis:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(170, 350, 180, 50);

        setBounds(0, 0, 475, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d2ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(nama.getText().equals("") || tinggi.getText().equals("") || berat.getText().equals("")){
    JOptionPane.showMessageDialog(null,"Form belum diisi");
}else if(lk.isSelected() || pr.isSelected()){
    try{
        Proses();
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,"Inputan ada yang salah");
    }
}else{
    JOptionPane.showMessageDialog(null,"Jenis Kelamin belum dipilih");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lkActionPerformed

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
nama.setText("");
tinggi.setText("");
berat.setText("");
ideal1.setText("");
d1.setText("");
d2.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int selectedOption = JOptionPane.showConfirmDialog(null,
 "Apakah anda akan menutup system?", "Tutup Aplikasi", JOptionPane.YES_NO_OPTION);
 if (selectedOption == JOptionPane.YES_OPTION) {
 System.exit(0);
 }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField ideal1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton lk;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton pr;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tinggi.getText());
        b1 = Double.valueOf(berat.getText());
        
        if(lk.isSelected()){
            h1 = (ti -100)*1;
        }else if(pr.isSelected()){
            h1 = (ti - 104) *1;
        }
        temp = h1+"";
        
        if(h1 < b1){
            ideal1.setText(temp);
            d1.setText("Maaf " + nama.getText() + ",sepertinya anda keelebihan lemak");
            d2.setText("Banyaklah berolahraga dan hindari narkoba");
        }else if(h1 > b1){
            ideal1.setText(temp);
            d1.setText("Maaf " + nama.getText() + ",sepertinya anda kekurangan lemak");
            d2.setText("Banyaklah berolahraga dan hindari rasa yang dulu pernah ada");
        }else{
            ideal1.setText(temp);
            d1.setText("Hallo " + nama.getText() + "badan anda sudah ideal");
            d2.setText("UMAK MBOIS!");
        }
    }
}
